// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package pbanalysis

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// empty message
type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

// message that only contains a value of bool
type BoolMessage struct {
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoolMessage) Reset()         { *m = BoolMessage{} }
func (m *BoolMessage) String() string { return proto.CompactTextString(m) }
func (*BoolMessage) ProtoMessage()    {}
func (*BoolMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *BoolMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolMessage.Unmarshal(m, b)
}
func (m *BoolMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolMessage.Marshal(b, m, deterministic)
}
func (m *BoolMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolMessage.Merge(m, src)
}
func (m *BoolMessage) XXX_Size() int {
	return xxx_messageInfo_BoolMessage.Size(m)
}
func (m *BoolMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BoolMessage proto.InternalMessageInfo

func (m *BoolMessage) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

// message that only contains a value of string
type StringMsg struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringMsg) Reset()         { *m = StringMsg{} }
func (m *StringMsg) String() string { return proto.CompactTextString(m) }
func (*StringMsg) ProtoMessage()    {}
func (*StringMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2}
}

func (m *StringMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringMsg.Unmarshal(m, b)
}
func (m *StringMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringMsg.Marshal(b, m, deterministic)
}
func (m *StringMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringMsg.Merge(m, src)
}
func (m *StringMsg) XXX_Size() int {
	return xxx_messageInfo_StringMsg.Size(m)
}
func (m *StringMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_StringMsg.DiscardUnknown(m)
}

var xxx_messageInfo_StringMsg proto.InternalMessageInfo

func (m *StringMsg) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// message that only contains two values of string
type String2Msg struct {
	Param1               string   `protobuf:"bytes,1,opt,name=param1,proto3" json:"param1,omitempty"`
	Param2               string   `protobuf:"bytes,2,opt,name=param2,proto3" json:"param2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *String2Msg) Reset()         { *m = String2Msg{} }
func (m *String2Msg) String() string { return proto.CompactTextString(m) }
func (*String2Msg) ProtoMessage()    {}
func (*String2Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{3}
}

func (m *String2Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_String2Msg.Unmarshal(m, b)
}
func (m *String2Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_String2Msg.Marshal(b, m, deterministic)
}
func (m *String2Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_String2Msg.Merge(m, src)
}
func (m *String2Msg) XXX_Size() int {
	return xxx_messageInfo_String2Msg.Size(m)
}
func (m *String2Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_String2Msg.DiscardUnknown(m)
}

var xxx_messageInfo_String2Msg proto.InternalMessageInfo

func (m *String2Msg) GetParam1() string {
	if m != nil {
		return m.Param1
	}
	return ""
}

func (m *String2Msg) GetParam2() string {
	if m != nil {
		return m.Param2
	}
	return ""
}

// message that only contains a value of int32
type Int32Msg struct {
	Value                int32    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int32Msg) Reset()         { *m = Int32Msg{} }
func (m *Int32Msg) String() string { return proto.CompactTextString(m) }
func (*Int32Msg) ProtoMessage()    {}
func (*Int32Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{4}
}

func (m *Int32Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int32Msg.Unmarshal(m, b)
}
func (m *Int32Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int32Msg.Marshal(b, m, deterministic)
}
func (m *Int32Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int32Msg.Merge(m, src)
}
func (m *Int32Msg) XXX_Size() int {
	return xxx_messageInfo_Int32Msg.Size(m)
}
func (m *Int32Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Int32Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Int32Msg proto.InternalMessageInfo

func (m *Int32Msg) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

// message that only contains a value of int64
type Int64Msg struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int64Msg) Reset()         { *m = Int64Msg{} }
func (m *Int64Msg) String() string { return proto.CompactTextString(m) }
func (*Int64Msg) ProtoMessage()    {}
func (*Int64Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{5}
}

func (m *Int64Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int64Msg.Unmarshal(m, b)
}
func (m *Int64Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int64Msg.Marshal(b, m, deterministic)
}
func (m *Int64Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64Msg.Merge(m, src)
}
func (m *Int64Msg) XXX_Size() int {
	return xxx_messageInfo_Int64Msg.Size(m)
}
func (m *Int64Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Int64Msg proto.InternalMessageInfo

func (m *Int64Msg) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

// Node message
type NodeMsg struct {
	ID                   int32            `protobuf:"varint,1,opt,name=iD,proto3" json:"iD,omitempty"`
	NodeID               string           `protobuf:"bytes,2,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	PubKey               string           `protobuf:"bytes,3,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	Owner                string           `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	ProfitAcc            string           `protobuf:"bytes,5,opt,name=profitAcc,proto3" json:"profitAcc,omitempty"`
	PoolID               string           `protobuf:"bytes,6,opt,name=poolID,proto3" json:"poolID,omitempty"`
	PoolOwner            string           `protobuf:"bytes,7,opt,name=poolOwner,proto3" json:"poolOwner,omitempty"`
	Quota                int64            `protobuf:"varint,8,opt,name=quota,proto3" json:"quota,omitempty"`
	Addrs                []string         `protobuf:"bytes,9,rep,name=addrs,proto3" json:"addrs,omitempty"`
	CPU                  int32            `protobuf:"varint,10,opt,name=cPU,proto3" json:"cPU,omitempty"`
	Memory               int32            `protobuf:"varint,11,opt,name=memory,proto3" json:"memory,omitempty"`
	Bandwidth            int32            `protobuf:"varint,12,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	MaxDataSpace         int64            `protobuf:"varint,13,opt,name=maxDataSpace,proto3" json:"maxDataSpace,omitempty"`
	AssignedSpace        int64            `protobuf:"varint,14,opt,name=assignedSpace,proto3" json:"assignedSpace,omitempty"`
	ProductiveSpace      int64            `protobuf:"varint,15,opt,name=productiveSpace,proto3" json:"productiveSpace,omitempty"`
	UsedSpace            int64            `protobuf:"varint,16,opt,name=usedSpace,proto3" json:"usedSpace,omitempty"`
	Weight               float64          `protobuf:"fixed64,17,opt,name=weight,proto3" json:"weight,omitempty"`
	Valid                int32            `protobuf:"varint,18,opt,name=valid,proto3" json:"valid,omitempty"`
	Relay                int32            `protobuf:"varint,19,opt,name=relay,proto3" json:"relay,omitempty"`
	Status               int32            `protobuf:"varint,20,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp            int64            `protobuf:"varint,21,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version              int32            `protobuf:"varint,22,opt,name=version,proto3" json:"version,omitempty"`
	Rebuilding           int32            `protobuf:"varint,23,opt,name=rebuilding,proto3" json:"rebuilding,omitempty"`
	RealSpace            int64            `protobuf:"varint,24,opt,name=realSpace,proto3" json:"realSpace,omitempty"`
	Tx                   int64            `protobuf:"varint,25,opt,name=tx,proto3" json:"tx,omitempty"`
	Rx                   int64            `protobuf:"varint,26,opt,name=rx,proto3" json:"rx,omitempty"`
	Ext                  string           `protobuf:"bytes,27,opt,name=ext,proto3" json:"ext,omitempty"`
	Uspaces              map[string]int64 `protobuf:"bytes,28,rep,name=uspaces,proto3" json:"uspaces,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *NodeMsg) Reset()         { *m = NodeMsg{} }
func (m *NodeMsg) String() string { return proto.CompactTextString(m) }
func (*NodeMsg) ProtoMessage()    {}
func (*NodeMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{6}
}

func (m *NodeMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeMsg.Unmarshal(m, b)
}
func (m *NodeMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeMsg.Marshal(b, m, deterministic)
}
func (m *NodeMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeMsg.Merge(m, src)
}
func (m *NodeMsg) XXX_Size() int {
	return xxx_messageInfo_NodeMsg.Size(m)
}
func (m *NodeMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeMsg.DiscardUnknown(m)
}

var xxx_messageInfo_NodeMsg proto.InternalMessageInfo

func (m *NodeMsg) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *NodeMsg) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

func (m *NodeMsg) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *NodeMsg) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *NodeMsg) GetProfitAcc() string {
	if m != nil {
		return m.ProfitAcc
	}
	return ""
}

func (m *NodeMsg) GetPoolID() string {
	if m != nil {
		return m.PoolID
	}
	return ""
}

func (m *NodeMsg) GetPoolOwner() string {
	if m != nil {
		return m.PoolOwner
	}
	return ""
}

func (m *NodeMsg) GetQuota() int64 {
	if m != nil {
		return m.Quota
	}
	return 0
}

func (m *NodeMsg) GetAddrs() []string {
	if m != nil {
		return m.Addrs
	}
	return nil
}

func (m *NodeMsg) GetCPU() int32 {
	if m != nil {
		return m.CPU
	}
	return 0
}

func (m *NodeMsg) GetMemory() int32 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *NodeMsg) GetBandwidth() int32 {
	if m != nil {
		return m.Bandwidth
	}
	return 0
}

func (m *NodeMsg) GetMaxDataSpace() int64 {
	if m != nil {
		return m.MaxDataSpace
	}
	return 0
}

func (m *NodeMsg) GetAssignedSpace() int64 {
	if m != nil {
		return m.AssignedSpace
	}
	return 0
}

func (m *NodeMsg) GetProductiveSpace() int64 {
	if m != nil {
		return m.ProductiveSpace
	}
	return 0
}

func (m *NodeMsg) GetUsedSpace() int64 {
	if m != nil {
		return m.UsedSpace
	}
	return 0
}

func (m *NodeMsg) GetWeight() float64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *NodeMsg) GetValid() int32 {
	if m != nil {
		return m.Valid
	}
	return 0
}

func (m *NodeMsg) GetRelay() int32 {
	if m != nil {
		return m.Relay
	}
	return 0
}

func (m *NodeMsg) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *NodeMsg) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *NodeMsg) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *NodeMsg) GetRebuilding() int32 {
	if m != nil {
		return m.Rebuilding
	}
	return 0
}

func (m *NodeMsg) GetRealSpace() int64 {
	if m != nil {
		return m.RealSpace
	}
	return 0
}

func (m *NodeMsg) GetTx() int64 {
	if m != nil {
		return m.Tx
	}
	return 0
}

func (m *NodeMsg) GetRx() int64 {
	if m != nil {
		return m.Rx
	}
	return 0
}

func (m *NodeMsg) GetExt() string {
	if m != nil {
		return m.Ext
	}
	return ""
}

func (m *NodeMsg) GetUspaces() map[string]int64 {
	if m != nil {
		return m.Uspaces
	}
	return nil
}

// SuperNode message
type SuperNodeMsg struct {
	ID                   int32    `protobuf:"varint,1,opt,name=iD,proto3" json:"iD,omitempty"`
	NodeID               string   `protobuf:"bytes,2,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	PubKey               string   `protobuf:"bytes,3,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	PrivKey              string   `protobuf:"bytes,4,opt,name=privKey,proto3" json:"privKey,omitempty"`
	Addrs                []string `protobuf:"bytes,5,rep,name=addrs,proto3" json:"addrs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SuperNodeMsg) Reset()         { *m = SuperNodeMsg{} }
func (m *SuperNodeMsg) String() string { return proto.CompactTextString(m) }
func (*SuperNodeMsg) ProtoMessage()    {}
func (*SuperNodeMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{7}
}

func (m *SuperNodeMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuperNodeMsg.Unmarshal(m, b)
}
func (m *SuperNodeMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuperNodeMsg.Marshal(b, m, deterministic)
}
func (m *SuperNodeMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuperNodeMsg.Merge(m, src)
}
func (m *SuperNodeMsg) XXX_Size() int {
	return xxx_messageInfo_SuperNodeMsg.Size(m)
}
func (m *SuperNodeMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SuperNodeMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SuperNodeMsg proto.InternalMessageInfo

func (m *SuperNodeMsg) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *SuperNodeMsg) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

func (m *SuperNodeMsg) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *SuperNodeMsg) GetPrivKey() string {
	if m != nil {
		return m.PrivKey
	}
	return ""
}

func (m *SuperNodeMsg) GetAddrs() []string {
	if m != nil {
		return m.Addrs
	}
	return nil
}

// NodeStat message
type NodeStatMsg struct {
	ActiveMiners         int64    `protobuf:"varint,1,opt,name=activeMiners,proto3" json:"activeMiners,omitempty"`
	TotalMiners          int64    `protobuf:"varint,2,opt,name=totalMiners,proto3" json:"totalMiners,omitempty"`
	MaxTotal             int64    `protobuf:"varint,3,opt,name=maxTotal,proto3" json:"maxTotal,omitempty"`
	AssignedTotal        int64    `protobuf:"varint,4,opt,name=assignedTotal,proto3" json:"assignedTotal,omitempty"`
	ProductiveTotal      int64    `protobuf:"varint,5,opt,name=productiveTotal,proto3" json:"productiveTotal,omitempty"`
	UsedTotal            int64    `protobuf:"varint,6,opt,name=usedTotal,proto3" json:"usedTotal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeStatMsg) Reset()         { *m = NodeStatMsg{} }
func (m *NodeStatMsg) String() string { return proto.CompactTextString(m) }
func (*NodeStatMsg) ProtoMessage()    {}
func (*NodeStatMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{8}
}

func (m *NodeStatMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeStatMsg.Unmarshal(m, b)
}
func (m *NodeStatMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeStatMsg.Marshal(b, m, deterministic)
}
func (m *NodeStatMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeStatMsg.Merge(m, src)
}
func (m *NodeStatMsg) XXX_Size() int {
	return xxx_messageInfo_NodeStatMsg.Size(m)
}
func (m *NodeStatMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeStatMsg.DiscardUnknown(m)
}

var xxx_messageInfo_NodeStatMsg proto.InternalMessageInfo

func (m *NodeStatMsg) GetActiveMiners() int64 {
	if m != nil {
		return m.ActiveMiners
	}
	return 0
}

func (m *NodeStatMsg) GetTotalMiners() int64 {
	if m != nil {
		return m.TotalMiners
	}
	return 0
}

func (m *NodeStatMsg) GetMaxTotal() int64 {
	if m != nil {
		return m.MaxTotal
	}
	return 0
}

func (m *NodeStatMsg) GetAssignedTotal() int64 {
	if m != nil {
		return m.AssignedTotal
	}
	return 0
}

func (m *NodeStatMsg) GetProductiveTotal() int64 {
	if m != nil {
		return m.ProductiveTotal
	}
	return 0
}

func (m *NodeStatMsg) GetUsedTotal() int64 {
	if m != nil {
		return m.UsedTotal
	}
	return 0
}

// SpotCheckTask message
type SpotCheckTaskMsg struct {
	ID                   int32    `protobuf:"varint,1,opt,name=iD,proto3" json:"iD,omitempty"`
	NodeID               string   `protobuf:"bytes,2,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Addr                 string   `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	VNI                  string   `protobuf:"bytes,4,opt,name=vNI,proto3" json:"vNI,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpotCheckTaskMsg) Reset()         { *m = SpotCheckTaskMsg{} }
func (m *SpotCheckTaskMsg) String() string { return proto.CompactTextString(m) }
func (*SpotCheckTaskMsg) ProtoMessage()    {}
func (*SpotCheckTaskMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{9}
}

func (m *SpotCheckTaskMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotCheckTaskMsg.Unmarshal(m, b)
}
func (m *SpotCheckTaskMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotCheckTaskMsg.Marshal(b, m, deterministic)
}
func (m *SpotCheckTaskMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotCheckTaskMsg.Merge(m, src)
}
func (m *SpotCheckTaskMsg) XXX_Size() int {
	return xxx_messageInfo_SpotCheckTaskMsg.Size(m)
}
func (m *SpotCheckTaskMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotCheckTaskMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SpotCheckTaskMsg proto.InternalMessageInfo

func (m *SpotCheckTaskMsg) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *SpotCheckTaskMsg) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

func (m *SpotCheckTaskMsg) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *SpotCheckTaskMsg) GetVNI() string {
	if m != nil {
		return m.VNI
	}
	return ""
}

// SpotCheckList message
type SpotCheckListMsg struct {
	TaskID               string              `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`
	TaskList             []*SpotCheckTaskMsg `protobuf:"bytes,2,rep,name=taskList,proto3" json:"taskList,omitempty"`
	Timestamp            int64               `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SpotCheckListMsg) Reset()         { *m = SpotCheckListMsg{} }
func (m *SpotCheckListMsg) String() string { return proto.CompactTextString(m) }
func (*SpotCheckListMsg) ProtoMessage()    {}
func (*SpotCheckListMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{10}
}

func (m *SpotCheckListMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotCheckListMsg.Unmarshal(m, b)
}
func (m *SpotCheckListMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotCheckListMsg.Marshal(b, m, deterministic)
}
func (m *SpotCheckListMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotCheckListMsg.Merge(m, src)
}
func (m *SpotCheckListMsg) XXX_Size() int {
	return xxx_messageInfo_SpotCheckListMsg.Size(m)
}
func (m *SpotCheckListMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotCheckListMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SpotCheckListMsg proto.InternalMessageInfo

func (m *SpotCheckListMsg) GetTaskID() string {
	if m != nil {
		return m.TaskID
	}
	return ""
}

func (m *SpotCheckListMsg) GetTaskList() []*SpotCheckTaskMsg {
	if m != nil {
		return m.TaskList
	}
	return nil
}

func (m *SpotCheckListMsg) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// response message of GetSpotCheckList function
type GetSpotCheckListResp struct {
	SpotCheckLists       []*SpotCheckListMsg `protobuf:"bytes,1,rep,name=spotCheckLists,proto3" json:"spotCheckLists,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetSpotCheckListResp) Reset()         { *m = GetSpotCheckListResp{} }
func (m *GetSpotCheckListResp) String() string { return proto.CompactTextString(m) }
func (*GetSpotCheckListResp) ProtoMessage()    {}
func (*GetSpotCheckListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{11}
}

func (m *GetSpotCheckListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSpotCheckListResp.Unmarshal(m, b)
}
func (m *GetSpotCheckListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSpotCheckListResp.Marshal(b, m, deterministic)
}
func (m *GetSpotCheckListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSpotCheckListResp.Merge(m, src)
}
func (m *GetSpotCheckListResp) XXX_Size() int {
	return xxx_messageInfo_GetSpotCheckListResp.Size(m)
}
func (m *GetSpotCheckListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSpotCheckListResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetSpotCheckListResp proto.InternalMessageInfo

func (m *GetSpotCheckListResp) GetSpotCheckLists() []*SpotCheckListMsg {
	if m != nil {
		return m.SpotCheckLists
	}
	return nil
}

// response message with multiple nodes
type NodesResp struct {
	Nodes                []*NodeMsg `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *NodesResp) Reset()         { *m = NodesResp{} }
func (m *NodesResp) String() string { return proto.CompactTextString(m) }
func (*NodesResp) ProtoMessage()    {}
func (*NodesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{12}
}

func (m *NodesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodesResp.Unmarshal(m, b)
}
func (m *NodesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodesResp.Marshal(b, m, deterministic)
}
func (m *NodesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodesResp.Merge(m, src)
}
func (m *NodesResp) XXX_Size() int {
	return xxx_messageInfo_NodesResp.Size(m)
}
func (m *NodesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_NodesResp.DiscardUnknown(m)
}

var xxx_messageInfo_NodesResp proto.InternalMessageInfo

func (m *NodesResp) GetNodes() []*NodeMsg {
	if m != nil {
		return m.Nodes
	}
	return nil
}

// response message with multiple supernodes
type SuperNodesResp struct {
	SuperNodes           []*SuperNodeMsg `protobuf:"bytes,1,rep,name=superNodes,proto3" json:"superNodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SuperNodesResp) Reset()         { *m = SuperNodesResp{} }
func (m *SuperNodesResp) String() string { return proto.CompactTextString(m) }
func (*SuperNodesResp) ProtoMessage()    {}
func (*SuperNodesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{13}
}

func (m *SuperNodesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuperNodesResp.Unmarshal(m, b)
}
func (m *SuperNodesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuperNodesResp.Marshal(b, m, deterministic)
}
func (m *SuperNodesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuperNodesResp.Merge(m, src)
}
func (m *SuperNodesResp) XXX_Size() int {
	return xxx_messageInfo_SuperNodesResp.Size(m)
}
func (m *SuperNodesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SuperNodesResp.DiscardUnknown(m)
}

var xxx_messageInfo_SuperNodesResp proto.InternalMessageInfo

func (m *SuperNodesResp) GetSuperNodes() []*SuperNodeMsg {
	if m != nil {
		return m.SuperNodes
	}
	return nil
}

// request message of IncrUsedSpace function
type IncrUsedSpaceReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Incr                 int64    `protobuf:"varint,2,opt,name=incr,proto3" json:"incr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncrUsedSpaceReq) Reset()         { *m = IncrUsedSpaceReq{} }
func (m *IncrUsedSpaceReq) String() string { return proto.CompactTextString(m) }
func (*IncrUsedSpaceReq) ProtoMessage()    {}
func (*IncrUsedSpaceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{14}
}

func (m *IncrUsedSpaceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncrUsedSpaceReq.Unmarshal(m, b)
}
func (m *IncrUsedSpaceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncrUsedSpaceReq.Marshal(b, m, deterministic)
}
func (m *IncrUsedSpaceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncrUsedSpaceReq.Merge(m, src)
}
func (m *IncrUsedSpaceReq) XXX_Size() int {
	return xxx_messageInfo_IncrUsedSpaceReq.Size(m)
}
func (m *IncrUsedSpaceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IncrUsedSpaceReq.DiscardUnknown(m)
}

var xxx_messageInfo_IncrUsedSpaceReq proto.InternalMessageInfo

func (m *IncrUsedSpaceReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *IncrUsedSpaceReq) GetIncr() int64 {
	if m != nil {
		return m.Incr
	}
	return 0
}

// request message of AllocNodes function
type AllocNodesReq struct {
	ShardCount           int32    `protobuf:"varint,1,opt,name=shardCount,proto3" json:"shardCount,omitempty"`
	ErrIDs               []int32  `protobuf:"varint,2,rep,packed,name=errIDs,proto3" json:"errIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllocNodesReq) Reset()         { *m = AllocNodesReq{} }
func (m *AllocNodesReq) String() string { return proto.CompactTextString(m) }
func (*AllocNodesReq) ProtoMessage()    {}
func (*AllocNodesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{15}
}

func (m *AllocNodesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllocNodesReq.Unmarshal(m, b)
}
func (m *AllocNodesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllocNodesReq.Marshal(b, m, deterministic)
}
func (m *AllocNodesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllocNodesReq.Merge(m, src)
}
func (m *AllocNodesReq) XXX_Size() int {
	return xxx_messageInfo_AllocNodesReq.Size(m)
}
func (m *AllocNodesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AllocNodesReq.DiscardUnknown(m)
}

var xxx_messageInfo_AllocNodesReq proto.InternalMessageInfo

func (m *AllocNodesReq) GetShardCount() int32 {
	if m != nil {
		return m.ShardCount
	}
	return 0
}

func (m *AllocNodesReq) GetErrIDs() []int32 {
	if m != nil {
		return m.ErrIDs
	}
	return nil
}

// request message of GetNodes function
type GetNodesReq struct {
	NodeIDs              []int32  `protobuf:"varint,1,rep,packed,name=nodeIDs,proto3" json:"nodeIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodesReq) Reset()         { *m = GetNodesReq{} }
func (m *GetNodesReq) String() string { return proto.CompactTextString(m) }
func (*GetNodesReq) ProtoMessage()    {}
func (*GetNodesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{16}
}

func (m *GetNodesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodesReq.Unmarshal(m, b)
}
func (m *GetNodesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodesReq.Marshal(b, m, deterministic)
}
func (m *GetNodesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodesReq.Merge(m, src)
}
func (m *GetNodesReq) XXX_Size() int {
	return xxx_messageInfo_GetNodesReq.Size(m)
}
func (m *GetNodesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodesReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodesReq proto.InternalMessageInfo

func (m *GetNodesReq) GetNodeIDs() []int32 {
	if m != nil {
		return m.NodeIDs
	}
	return nil
}

// request message of AddDNI function
type DNIReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Shard                []byte   `protobuf:"bytes,2,opt,name=shard,proto3" json:"shard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DNIReq) Reset()         { *m = DNIReq{} }
func (m *DNIReq) String() string { return proto.CompactTextString(m) }
func (*DNIReq) ProtoMessage()    {}
func (*DNIReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{17}
}

func (m *DNIReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DNIReq.Unmarshal(m, b)
}
func (m *DNIReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DNIReq.Marshal(b, m, deterministic)
}
func (m *DNIReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DNIReq.Merge(m, src)
}
func (m *DNIReq) XXX_Size() int {
	return xxx_messageInfo_DNIReq.Size(m)
}
func (m *DNIReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DNIReq.DiscardUnknown(m)
}

var xxx_messageInfo_DNIReq proto.InternalMessageInfo

func (m *DNIReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DNIReq) GetShard() []byte {
	if m != nil {
		return m.Shard
	}
	return nil
}

// request message of UpdateTaskStatus function
type UpdateTaskStatusReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InvalidNode          int32    `protobuf:"varint,2,opt,name=invalidNode,proto3" json:"invalidNode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTaskStatusReq) Reset()         { *m = UpdateTaskStatusReq{} }
func (m *UpdateTaskStatusReq) String() string { return proto.CompactTextString(m) }
func (*UpdateTaskStatusReq) ProtoMessage()    {}
func (*UpdateTaskStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{18}
}

func (m *UpdateTaskStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTaskStatusReq.Unmarshal(m, b)
}
func (m *UpdateTaskStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTaskStatusReq.Marshal(b, m, deterministic)
}
func (m *UpdateTaskStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTaskStatusReq.Merge(m, src)
}
func (m *UpdateTaskStatusReq) XXX_Size() int {
	return xxx_messageInfo_UpdateTaskStatusReq.Size(m)
}
func (m *UpdateTaskStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTaskStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTaskStatusReq proto.InternalMessageInfo

func (m *UpdateTaskStatusReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateTaskStatusReq) GetInvalidNode() int32 {
	if m != nil {
		return m.InvalidNode
	}
	return 0
}

// ShardCount message
type ShardCountMsg struct {
	ID                   int32    `protobuf:"varint,1,opt,name=iD,proto3" json:"iD,omitempty"`
	Cnt                  int64    `protobuf:"varint,2,opt,name=cnt,proto3" json:"cnt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShardCountMsg) Reset()         { *m = ShardCountMsg{} }
func (m *ShardCountMsg) String() string { return proto.CompactTextString(m) }
func (*ShardCountMsg) ProtoMessage()    {}
func (*ShardCountMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{19}
}

func (m *ShardCountMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardCountMsg.Unmarshal(m, b)
}
func (m *ShardCountMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardCountMsg.Marshal(b, m, deterministic)
}
func (m *ShardCountMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardCountMsg.Merge(m, src)
}
func (m *ShardCountMsg) XXX_Size() int {
	return xxx_messageInfo_ShardCountMsg.Size(m)
}
func (m *ShardCountMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardCountMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ShardCountMsg proto.InternalMessageInfo

func (m *ShardCountMsg) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ShardCountMsg) GetCnt() int64 {
	if m != nil {
		return m.Cnt
	}
	return 0
}

// request message of GetInvalidNodes function
type GetInvalidNodesResp struct {
	ShardCounts          []*ShardCountMsg `protobuf:"bytes,1,rep,name=shardCounts,proto3" json:"shardCounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetInvalidNodesResp) Reset()         { *m = GetInvalidNodesResp{} }
func (m *GetInvalidNodesResp) String() string { return proto.CompactTextString(m) }
func (*GetInvalidNodesResp) ProtoMessage()    {}
func (*GetInvalidNodesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{20}
}

func (m *GetInvalidNodesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInvalidNodesResp.Unmarshal(m, b)
}
func (m *GetInvalidNodesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInvalidNodesResp.Marshal(b, m, deterministic)
}
func (m *GetInvalidNodesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInvalidNodesResp.Merge(m, src)
}
func (m *GetInvalidNodesResp) XXX_Size() int {
	return xxx_messageInfo_GetInvalidNodesResp.Size(m)
}
func (m *GetInvalidNodesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInvalidNodesResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetInvalidNodesResp proto.InternalMessageInfo

func (m *GetInvalidNodesResp) GetShardCounts() []*ShardCountMsg {
	if m != nil {
		return m.ShardCounts
	}
	return nil
}

// request message of GetInvalidNodes function
type GetRebuildItemReq struct {
	MinerID              int32    `protobuf:"varint,1,opt,name=minerID,proto3" json:"minerID,omitempty"`
	Index                int64    `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Total                int64    `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRebuildItemReq) Reset()         { *m = GetRebuildItemReq{} }
func (m *GetRebuildItemReq) String() string { return proto.CompactTextString(m) }
func (*GetRebuildItemReq) ProtoMessage()    {}
func (*GetRebuildItemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{21}
}

func (m *GetRebuildItemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRebuildItemReq.Unmarshal(m, b)
}
func (m *GetRebuildItemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRebuildItemReq.Marshal(b, m, deterministic)
}
func (m *GetRebuildItemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRebuildItemReq.Merge(m, src)
}
func (m *GetRebuildItemReq) XXX_Size() int {
	return xxx_messageInfo_GetRebuildItemReq.Size(m)
}
func (m *GetRebuildItemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRebuildItemReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetRebuildItemReq proto.InternalMessageInfo

func (m *GetRebuildItemReq) GetMinerID() int32 {
	if m != nil {
		return m.MinerID
	}
	return 0
}

func (m *GetRebuildItemReq) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *GetRebuildItemReq) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

// response message of GetInvalidNodes function
type GetRebuildItemResp struct {
	Node                 *NodeMsg `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Shards               [][]byte `protobuf:"bytes,2,rep,name=shards,proto3" json:"shards,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRebuildItemResp) Reset()         { *m = GetRebuildItemResp{} }
func (m *GetRebuildItemResp) String() string { return proto.CompactTextString(m) }
func (*GetRebuildItemResp) ProtoMessage()    {}
func (*GetRebuildItemResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{22}
}

func (m *GetRebuildItemResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRebuildItemResp.Unmarshal(m, b)
}
func (m *GetRebuildItemResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRebuildItemResp.Marshal(b, m, deterministic)
}
func (m *GetRebuildItemResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRebuildItemResp.Merge(m, src)
}
func (m *GetRebuildItemResp) XXX_Size() int {
	return xxx_messageInfo_GetRebuildItemResp.Size(m)
}
func (m *GetRebuildItemResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRebuildItemResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetRebuildItemResp proto.InternalMessageInfo

func (m *GetRebuildItemResp) GetNode() *NodeMsg {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *GetRebuildItemResp) GetShards() [][]byte {
	if m != nil {
		return m.Shards
	}
	return nil
}

type DownloadShardRequest struct {
	VHF                  []byte   `protobuf:"bytes,1,opt,name=VHF,proto3" json:"VHF,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadShardRequest) Reset()         { *m = DownloadShardRequest{} }
func (m *DownloadShardRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadShardRequest) ProtoMessage()    {}
func (*DownloadShardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{23}
}

func (m *DownloadShardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadShardRequest.Unmarshal(m, b)
}
func (m *DownloadShardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadShardRequest.Marshal(b, m, deterministic)
}
func (m *DownloadShardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadShardRequest.Merge(m, src)
}
func (m *DownloadShardRequest) XXX_Size() int {
	return xxx_messageInfo_DownloadShardRequest.Size(m)
}
func (m *DownloadShardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadShardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadShardRequest proto.InternalMessageInfo

func (m *DownloadShardRequest) GetVHF() []byte {
	if m != nil {
		return m.VHF
	}
	return nil
}

type DownloadShardResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadShardResponse) Reset()         { *m = DownloadShardResponse{} }
func (m *DownloadShardResponse) String() string { return proto.CompactTextString(m) }
func (*DownloadShardResponse) ProtoMessage()    {}
func (*DownloadShardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{24}
}

func (m *DownloadShardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadShardResponse.Unmarshal(m, b)
}
func (m *DownloadShardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadShardResponse.Marshal(b, m, deterministic)
}
func (m *DownloadShardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadShardResponse.Merge(m, src)
}
func (m *DownloadShardResponse) XXX_Size() int {
	return xxx_messageInfo_DownloadShardResponse.Size(m)
}
func (m *DownloadShardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadShardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadShardResponse proto.InternalMessageInfo

func (m *DownloadShardResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SignMessage struct {
	AccountName          string   `protobuf:"bytes,1,opt,name=accountName,proto3" json:"accountName,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Signature            string   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignMessage) Reset()         { *m = SignMessage{} }
func (m *SignMessage) String() string { return proto.CompactTextString(m) }
func (*SignMessage) ProtoMessage()    {}
func (*SignMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{25}
}

func (m *SignMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignMessage.Unmarshal(m, b)
}
func (m *SignMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignMessage.Marshal(b, m, deterministic)
}
func (m *SignMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignMessage.Merge(m, src)
}
func (m *SignMessage) XXX_Size() int {
	return xxx_messageInfo_SignMessage.Size(m)
}
func (m *SignMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SignMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SignMessage proto.InternalMessageInfo

func (m *SignMessage) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

func (m *SignMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SignMessage) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type UpdateUspaceMessage struct {
	NodeID               int32    `protobuf:"varint,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	FromNodeID           int32    `protobuf:"varint,2,opt,name=fromNodeID,proto3" json:"fromNodeID,omitempty"`
	Uspace               int64    `protobuf:"varint,3,opt,name=uspace,proto3" json:"uspace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUspaceMessage) Reset()         { *m = UpdateUspaceMessage{} }
func (m *UpdateUspaceMessage) String() string { return proto.CompactTextString(m) }
func (*UpdateUspaceMessage) ProtoMessage()    {}
func (*UpdateUspaceMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{26}
}

func (m *UpdateUspaceMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUspaceMessage.Unmarshal(m, b)
}
func (m *UpdateUspaceMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUspaceMessage.Marshal(b, m, deterministic)
}
func (m *UpdateUspaceMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUspaceMessage.Merge(m, src)
}
func (m *UpdateUspaceMessage) XXX_Size() int {
	return xxx_messageInfo_UpdateUspaceMessage.Size(m)
}
func (m *UpdateUspaceMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUspaceMessage.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUspaceMessage proto.InternalMessageInfo

func (m *UpdateUspaceMessage) GetNodeID() int32 {
	if m != nil {
		return m.NodeID
	}
	return 0
}

func (m *UpdateUspaceMessage) GetFromNodeID() int32 {
	if m != nil {
		return m.FromNodeID
	}
	return 0
}

func (m *UpdateUspaceMessage) GetUspace() int64 {
	if m != nil {
		return m.Uspace
	}
	return 0
}

type PunishMessage struct {
	NodeID               int32           `protobuf:"varint,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Type                 int32           `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	NeedPunish           bool            `protobuf:"varint,3,opt,name=needPunish,proto3" json:"needPunish,omitempty"`
	Count                int32           `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Rule                 map[int32]int32 `protobuf:"bytes,5,rep,name=rule,proto3" json:"rule,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PunishMessage) Reset()         { *m = PunishMessage{} }
func (m *PunishMessage) String() string { return proto.CompactTextString(m) }
func (*PunishMessage) ProtoMessage()    {}
func (*PunishMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{27}
}

func (m *PunishMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PunishMessage.Unmarshal(m, b)
}
func (m *PunishMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PunishMessage.Marshal(b, m, deterministic)
}
func (m *PunishMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PunishMessage.Merge(m, src)
}
func (m *PunishMessage) XXX_Size() int {
	return xxx_messageInfo_PunishMessage.Size(m)
}
func (m *PunishMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PunishMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PunishMessage proto.InternalMessageInfo

func (m *PunishMessage) GetNodeID() int32 {
	if m != nil {
		return m.NodeID
	}
	return 0
}

func (m *PunishMessage) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *PunishMessage) GetNeedPunish() bool {
	if m != nil {
		return m.NeedPunish
	}
	return false
}

func (m *PunishMessage) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *PunishMessage) GetRule() map[int32]int32 {
	if m != nil {
		return m.Rule
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "pbanalysis.Empty")
	proto.RegisterType((*BoolMessage)(nil), "pbanalysis.BoolMessage")
	proto.RegisterType((*StringMsg)(nil), "pbanalysis.StringMsg")
	proto.RegisterType((*String2Msg)(nil), "pbanalysis.String2Msg")
	proto.RegisterType((*Int32Msg)(nil), "pbanalysis.Int32Msg")
	proto.RegisterType((*Int64Msg)(nil), "pbanalysis.Int64Msg")
	proto.RegisterType((*NodeMsg)(nil), "pbanalysis.NodeMsg")
	proto.RegisterMapType((map[string]int64)(nil), "pbanalysis.NodeMsg.UspacesEntry")
	proto.RegisterType((*SuperNodeMsg)(nil), "pbanalysis.SuperNodeMsg")
	proto.RegisterType((*NodeStatMsg)(nil), "pbanalysis.NodeStatMsg")
	proto.RegisterType((*SpotCheckTaskMsg)(nil), "pbanalysis.SpotCheckTaskMsg")
	proto.RegisterType((*SpotCheckListMsg)(nil), "pbanalysis.SpotCheckListMsg")
	proto.RegisterType((*GetSpotCheckListResp)(nil), "pbanalysis.GetSpotCheckListResp")
	proto.RegisterType((*NodesResp)(nil), "pbanalysis.NodesResp")
	proto.RegisterType((*SuperNodesResp)(nil), "pbanalysis.SuperNodesResp")
	proto.RegisterType((*IncrUsedSpaceReq)(nil), "pbanalysis.IncrUsedSpaceReq")
	proto.RegisterType((*AllocNodesReq)(nil), "pbanalysis.AllocNodesReq")
	proto.RegisterType((*GetNodesReq)(nil), "pbanalysis.GetNodesReq")
	proto.RegisterType((*DNIReq)(nil), "pbanalysis.DNIReq")
	proto.RegisterType((*UpdateTaskStatusReq)(nil), "pbanalysis.UpdateTaskStatusReq")
	proto.RegisterType((*ShardCountMsg)(nil), "pbanalysis.ShardCountMsg")
	proto.RegisterType((*GetInvalidNodesResp)(nil), "pbanalysis.GetInvalidNodesResp")
	proto.RegisterType((*GetRebuildItemReq)(nil), "pbanalysis.GetRebuildItemReq")
	proto.RegisterType((*GetRebuildItemResp)(nil), "pbanalysis.GetRebuildItemResp")
	proto.RegisterType((*DownloadShardRequest)(nil), "pbanalysis.DownloadShardRequest")
	proto.RegisterType((*DownloadShardResponse)(nil), "pbanalysis.DownloadShardResponse")
	proto.RegisterType((*SignMessage)(nil), "pbanalysis.SignMessage")
	proto.RegisterType((*UpdateUspaceMessage)(nil), "pbanalysis.UpdateUspaceMessage")
	proto.RegisterType((*PunishMessage)(nil), "pbanalysis.PunishMessage")
	proto.RegisterMapType((map[int32]int32)(nil), "pbanalysis.PunishMessage.RuleEntry")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 1347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x5f, 0x6f, 0x1b, 0x45,
	0x10, 0xaf, 0x9d, 0x5c, 0x12, 0x8f, 0x9d, 0x34, 0xbd, 0xa4, 0xed, 0x36, 0x54, 0xc5, 0x6c, 0x91,
	0x1a, 0x84, 0x64, 0xa9, 0x2e, 0x6a, 0xab, 0x82, 0x90, 0xda, 0xba, 0xa4, 0x06, 0x1a, 0xa2, 0x73,
	0x83, 0x84, 0xc4, 0x03, 0x1b, 0xdf, 0xd6, 0x39, 0xe5, 0xfe, 0xe5, 0x76, 0x2f, 0xb1, 0x5f, 0x78,
	0xe0, 0x3b, 0xf1, 0x69, 0x10, 0x4f, 0x7c, 0x11, 0x34, 0xb3, 0x7b, 0xe7, 0xb5, 0x9b, 0x82, 0x90,
	0x78, 0xdb, 0xdf, 0xef, 0x7e, 0x3b, 0x33, 0x3b, 0x33, 0x3b, 0x6b, 0x43, 0x5b, 0xcf, 0x72, 0xa9,
	0x7a, 0x79, 0x91, 0xe9, 0xcc, 0x87, 0xfc, 0x44, 0xa4, 0x22, 0x9e, 0xa9, 0x48, 0xf1, 0x75, 0xf0,
	0x5e, 0x25, 0xb9, 0x9e, 0xf1, 0xfb, 0xd0, 0x7e, 0x91, 0x65, 0xf1, 0x1b, 0xa9, 0x94, 0x98, 0x48,
	0x7f, 0x17, 0xbc, 0x0b, 0x11, 0x97, 0x92, 0x35, 0xba, 0x8d, 0xfd, 0x8d, 0xc0, 0x00, 0xfe, 0x09,
	0xb4, 0x46, 0xba, 0x88, 0xd2, 0xc9, 0x1b, 0x35, 0x59, 0x94, 0xb4, 0x2a, 0xc9, 0x57, 0x00, 0x46,
	0xd2, 0x47, 0xcd, 0x2d, 0x58, 0xcb, 0x45, 0x21, 0x92, 0x87, 0x56, 0x64, 0x51, 0xcd, 0xf7, 0x59,
	0xd3, 0xe1, 0xfb, 0xbc, 0x0b, 0x1b, 0xc3, 0x54, 0x3f, 0xea, 0xbf, 0x67, 0xdf, 0xab, 0xec, 0x1b,
	0xc5, 0xe3, 0x2f, 0xde, 0x53, 0xac, 0x54, 0x8a, 0xdf, 0xd7, 0x60, 0xfd, 0x30, 0x0b, 0x25, 0x2a,
	0xb6, 0xa0, 0x19, 0x0d, 0xac, 0x81, 0x66, 0x34, 0x40, 0xbf, 0x69, 0x16, 0xca, 0xe1, 0xa0, 0xf2,
	0x6b, 0x10, 0xc5, 0x53, 0x9e, 0x7c, 0x27, 0x67, 0x6c, 0xc5, 0xc6, 0x43, 0x08, 0x3d, 0x64, 0x97,
	0xa9, 0x2c, 0xd8, 0xaa, 0x39, 0x23, 0x01, 0xff, 0x2e, 0xb4, 0xf2, 0x22, 0x7b, 0x17, 0xe9, 0xe7,
	0xe3, 0x31, 0xf3, 0xe8, 0xcb, 0x9c, 0x20, 0x5b, 0x59, 0x16, 0x0f, 0x07, 0x6c, 0xcd, 0xda, 0x22,
	0x44, 0xbb, 0xb2, 0x2c, 0xfe, 0x81, 0xec, 0xad, 0xdb, 0x5d, 0x15, 0x81, 0x9e, 0xce, 0xcb, 0x4c,
	0x0b, 0xb6, 0x61, 0xce, 0x42, 0x00, 0x59, 0x11, 0x86, 0x85, 0x62, 0xad, 0xee, 0x0a, 0xfa, 0x27,
	0xe0, 0x6f, 0xc3, 0xca, 0xf8, 0xe8, 0x98, 0x01, 0x1d, 0x0b, 0x97, 0xe8, 0x33, 0x91, 0x49, 0x56,
	0xcc, 0x58, 0x9b, 0x48, 0x8b, 0xd0, 0xe7, 0x89, 0x48, 0xc3, 0xcb, 0x28, 0xd4, 0xa7, 0xac, 0x43,
	0x9f, 0xe6, 0x84, 0xcf, 0xa1, 0x93, 0x88, 0xe9, 0x40, 0x68, 0x31, 0xca, 0xc5, 0x58, 0xb2, 0x4d,
	0x72, 0xbd, 0xc0, 0xf9, 0x9f, 0xc2, 0xa6, 0x50, 0x2a, 0x9a, 0xa4, 0x32, 0x34, 0xa2, 0x2d, 0x12,
	0x2d, 0x92, 0xfe, 0x3e, 0x5c, 0xcf, 0x8b, 0x2c, 0x2c, 0xc7, 0x3a, 0xba, 0x90, 0x46, 0x77, 0x9d,
	0x74, 0xcb, 0x34, 0x46, 0x54, 0xaa, 0xca, 0xd6, 0x36, 0x69, 0xe6, 0x04, 0x9e, 0xe3, 0x52, 0x46,
	0x93, 0x53, 0xcd, 0x6e, 0x74, 0x1b, 0xfb, 0x8d, 0xc0, 0x22, 0x5b, 0xe9, 0x28, 0x64, 0x7e, 0xdd,
	0x0b, 0x51, 0x88, 0x6c, 0x21, 0x63, 0x31, 0x63, 0x3b, 0x86, 0x25, 0x80, 0x36, 0x94, 0x16, 0xba,
	0x54, 0x6c, 0xd7, 0xe4, 0xc2, 0x20, 0xf4, 0xac, 0xa3, 0x44, 0x2a, 0x2d, 0x92, 0x9c, 0xdd, 0x34,
	0x9e, 0x6b, 0xc2, 0x67, 0xb0, 0x7e, 0x21, 0x0b, 0x15, 0x65, 0x29, 0xbb, 0x45, 0xdb, 0x2a, 0xe8,
	0xdf, 0x03, 0x28, 0xe4, 0x49, 0x19, 0xc5, 0x61, 0x94, 0x4e, 0xd8, 0x6d, 0xfa, 0xe8, 0x30, 0x68,
	0xb7, 0x90, 0x22, 0x36, 0x27, 0x62, 0xc6, 0x6e, 0x4d, 0x60, 0x07, 0xea, 0x29, 0xbb, 0x43, 0x74,
	0x53, 0x4f, 0x11, 0x17, 0x53, 0xb6, 0x67, 0x70, 0x31, 0xc5, 0x5a, 0xca, 0xa9, 0x66, 0x1f, 0x51,
	0x3f, 0xe0, 0xd2, 0x7f, 0x06, 0xeb, 0xa5, 0xc2, 0xbd, 0x8a, 0xdd, 0xed, 0xae, 0xec, 0xb7, 0xfb,
	0xdd, 0xde, 0xfc, 0xc2, 0xf6, 0x6c, 0x67, 0xf7, 0x8e, 0x8d, 0xe4, 0x55, 0xaa, 0x8b, 0x59, 0x50,
	0x6d, 0xd8, 0x7b, 0x06, 0x1d, 0xf7, 0x03, 0x5a, 0x3f, 0x93, 0x33, 0x7b, 0xf9, 0x70, 0x39, 0xbf,
	0x33, 0x4d, 0xe7, 0xce, 0x3c, 0x6b, 0x3e, 0x6d, 0xf0, 0x5f, 0xa1, 0x33, 0x2a, 0x73, 0x59, 0xfc,
	0x5f, 0x77, 0x87, 0xc1, 0x7a, 0x5e, 0x44, 0x17, 0xf8, 0xc1, 0xdc, 0x9e, 0x0a, 0xce, 0xbb, 0xda,
	0x73, 0xba, 0x9a, 0xff, 0xd9, 0x80, 0x36, 0xfa, 0x1e, 0x69, 0xa1, 0xd1, 0x3f, 0x87, 0x8e, 0xa0,
	0xc6, 0x79, 0x13, 0xa5, 0xb2, 0x50, 0xf6, 0x92, 0x2f, 0x70, 0x7e, 0x17, 0xda, 0x3a, 0xd3, 0x22,
	0xb6, 0x12, 0x73, 0x26, 0x97, 0xf2, 0xf7, 0x60, 0x23, 0x11, 0xd3, 0xb7, 0xc8, 0x50, 0x7c, 0x2b,
	0x41, 0x8d, 0xdd, 0xde, 0x36, 0x82, 0xd5, 0xc5, 0xde, 0x36, 0xaa, 0x85, 0xde, 0x36, 0x3a, 0x6f,
	0xb9, 0xb7, 0x8d, 0xd2, 0xf6, 0xb6, 0xd1, 0xac, 0xcd, 0x7b, 0x9b, 0x08, 0xfe, 0x0b, 0x6c, 0x8f,
	0xf2, 0x4c, 0xbf, 0x3c, 0x95, 0xe3, 0xb3, 0xb7, 0x42, 0x9d, 0xfd, 0x97, 0x1c, 0xfb, 0xb0, 0x8a,
	0x49, 0xb2, 0x19, 0xa6, 0x35, 0xd6, 0xf6, 0xe2, 0x70, 0x68, 0x73, 0x8b, 0x4b, 0xfe, 0x5b, 0xc3,
	0x71, 0xf1, 0x7d, 0xa4, 0xb4, 0x1d, 0xc1, 0x5a, 0xa8, 0xb3, 0xe1, 0xa0, 0x1a, 0xc1, 0x06, 0xf9,
	0x4f, 0x61, 0x03, 0x57, 0x28, 0x63, 0x4d, 0xea, 0xb3, 0xbb, 0x6e, 0x9f, 0x2d, 0x87, 0x1a, 0xd4,
	0xea, 0xc5, 0x8b, 0xb4, 0xb2, 0x74, 0x91, 0xf8, 0xcf, 0xb0, 0x7b, 0x20, 0xf5, 0x42, 0x18, 0x81,
	0x54, 0xb9, 0x3f, 0x80, 0x2d, 0xe5, 0x92, 0x58, 0xd0, 0x0f, 0x7b, 0xb5, 0xd1, 0x07, 0x4b, 0x7b,
	0xf8, 0x63, 0x68, 0x61, 0x8f, 0x28, 0x32, 0xf9, 0x19, 0x78, 0x98, 0x9f, 0xca, 0xd2, 0xce, 0x15,
	0xf7, 0x24, 0x30, 0x0a, 0xfe, 0x2d, 0x6c, 0xd5, 0xcd, 0x6d, 0x36, 0x3f, 0x05, 0x50, 0x35, 0x63,
	0x2d, 0xb0, 0x85, 0x58, 0x9c, 0xcb, 0x10, 0x38, 0x5a, 0xfe, 0x18, 0xb6, 0x87, 0xe9, 0xb8, 0x38,
	0xae, 0xa6, 0x56, 0x20, 0xcf, 0xa9, 0x90, 0x61, 0x5d, 0xc8, 0x10, 0x0b, 0x16, 0xa5, 0xe3, 0xc2,
	0x76, 0x24, 0xad, 0xf9, 0x01, 0x6c, 0x3e, 0x8f, 0xe3, 0x6c, 0x6c, 0x63, 0x38, 0xc7, 0xc9, 0xa2,
	0x4e, 0x45, 0x11, 0xbe, 0xcc, 0xca, 0x54, 0xdb, 0xcd, 0x0e, 0x83, 0xa5, 0x93, 0x45, 0x31, 0x1c,
	0x28, 0x2a, 0x90, 0x17, 0x58, 0xc4, 0x1f, 0x40, 0xfb, 0x40, 0xea, 0xda, 0x0c, 0x83, 0x75, 0xd3,
	0x26, 0xe6, 0x18, 0x5e, 0x50, 0x41, 0xde, 0x83, 0xb5, 0xc1, 0xe1, 0xf0, 0xaa, 0xf8, 0x76, 0xc1,
	0x23, 0x47, 0x14, 0x60, 0x27, 0x30, 0x80, 0x1f, 0xc0, 0xce, 0x71, 0x1e, 0x0a, 0x2d, 0xb1, 0xe8,
	0x23, 0x1a, 0x9b, 0x8b, 0x9b, 0x5b, 0xb4, 0xb9, 0x0b, 0xed, 0x28, 0xa5, 0x11, 0x8c, 0x31, 0x90,
	0x09, 0x2f, 0x70, 0x29, 0xfe, 0x10, 0x36, 0x47, 0xf5, 0x39, 0xae, 0x6a, 0x74, 0x7c, 0xc2, 0x52,
	0x6d, 0xd3, 0x83, 0x4b, 0x1e, 0xc0, 0xce, 0x81, 0xd4, 0xc3, 0xb9, 0x11, 0x53, 0xa6, 0x2f, 0xa1,
	0x3d, 0xcf, 0x48, 0x55, 0xa7, 0x3b, 0x0b, 0x75, 0x72, 0x1d, 0x05, 0xae, 0x9a, 0xff, 0x04, 0x37,
	0x0e, 0xa4, 0x0e, 0xcc, 0xac, 0x1e, 0x6a, 0x99, 0xd8, 0x74, 0x25, 0x38, 0x1b, 0x86, 0x55, 0x3c,
	0x15, 0xc4, 0xa4, 0x44, 0x69, 0x28, 0xa7, 0xd5, 0x6c, 0x24, 0x80, 0xac, 0x76, 0xc6, 0x87, 0x01,
	0xfc, 0x18, 0xfc, 0x65, 0xd3, 0x2a, 0xf7, 0x1f, 0xc0, 0x2a, 0xe6, 0x9e, 0x0c, 0x7f, 0xa0, 0x21,
	0x49, 0x40, 0x8f, 0x14, 0x06, 0x6a, 0x4a, 0xdb, 0x09, 0x2c, 0xe2, 0xfb, 0xb0, 0x3b, 0xc8, 0x2e,
	0xd3, 0x38, 0x13, 0x21, 0x9d, 0x2b, 0x90, 0xe7, 0xa5, 0x54, 0x1a, 0xf3, 0xf5, 0xe3, 0xeb, 0x6f,
	0xc8, 0x6e, 0x27, 0xc0, 0x25, 0xff, 0x1c, 0x6e, 0x2e, 0x29, 0x55, 0x9e, 0xa5, 0x4a, 0x62, 0xeb,
	0x85, 0x42, 0x0b, 0xab, 0xa5, 0x35, 0x17, 0xd0, 0x1e, 0x45, 0x93, 0xb4, 0xfa, 0x75, 0xd7, 0x85,
	0xb6, 0x18, 0x8f, 0x31, 0x47, 0x87, 0x22, 0xa9, 0x7e, 0xc0, 0xb9, 0x54, 0x6d, 0xa4, 0x39, 0x37,
	0x82, 0xf7, 0x1e, 0xe7, 0xa2, 0xd0, 0x65, 0x21, 0xed, 0x24, 0x9a, 0x13, 0x5c, 0x56, 0xbd, 0x63,
	0x1e, 0xa0, 0xca, 0xd5, 0x7c, 0xa2, 0x99, 0x64, 0x57, 0x13, 0xed, 0x1e, 0xc0, 0xbb, 0x22, 0x4b,
	0x0e, 0xe7, 0xd3, 0xce, 0x0b, 0x1c, 0x06, 0xf7, 0x99, 0x47, 0xcd, 0xa6, 0xdd, 0x22, 0xfe, 0x57,
	0x03, 0x36, 0x8f, 0xca, 0x34, 0x52, 0xa7, 0xff, 0xe6, 0xc1, 0x87, 0x55, 0xfc, 0xd5, 0x6b, 0x6d,
	0xd3, 0x1a, 0xbd, 0xa6, 0x52, 0x86, 0xc6, 0x00, 0x59, 0xde, 0x08, 0x1c, 0x06, 0x6b, 0x4d, 0x39,
	0xa0, 0xa9, 0xea, 0x05, 0x06, 0xf8, 0x4f, 0x60, 0xb5, 0x28, 0x63, 0x49, 0xcf, 0x55, 0xbb, 0x7f,
	0xdf, 0xad, 0xea, 0x42, 0x28, 0xbd, 0xa0, 0x8c, 0xa5, 0x79, 0x91, 0x69, 0xc3, 0xde, 0x13, 0x68,
	0xd5, 0x94, 0xfb, 0x16, 0x7b, 0x57, 0xbc, 0xc5, 0x9e, 0xf3, 0x16, 0xf7, 0xff, 0x68, 0xc0, 0xc6,
	0x73, 0xeb, 0xc3, 0x7f, 0x05, 0xdb, 0xcb, 0x13, 0xd5, 0xbf, 0xe1, 0x06, 0x41, 0xbf, 0xe0, 0xf7,
	0xfe, 0x71, 0x90, 0xf2, 0x6b, 0xfe, 0xd7, 0xb0, 0x35, 0x54, 0xf4, 0xc0, 0xca, 0x58, 0x8e, 0xb5,
	0x0c, 0xaf, 0x32, 0x72, 0xdb, 0xa5, 0x9c, 0x3f, 0x04, 0xfc, 0x9a, 0xff, 0x1a, 0xb6, 0x97, 0x87,
	0x83, 0xff, 0xb1, 0x2b, 0xbf, 0x62, 0x74, 0xec, 0xbd, 0xef, 0x82, 0x5f, 0x7b, 0xf1, 0x04, 0x78,
	0x94, 0xf5, 0x66, 0x99, 0xd6, 0x62, 0x7c, 0x2a, 0xa2, 0xb4, 0x87, 0x15, 0x4b, 0x26, 0x89, 0xee,
	0xd5, 0xd2, 0xfc, 0xe4, 0xc5, 0x66, 0x95, 0x80, 0x23, 0xfc, 0xd7, 0xf2, 0xba, 0x71, 0xd4, 0x38,
	0x59, 0xa3, 0x3f, 0x30, 0x8f, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x6e, 0x82, 0x71, 0xb3, 0xcf,
	0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AnalysisClient is the client API for Analysis service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AnalysisClient interface {
	GetSpotCheckList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SpotCheckListMsg, error)
	IsNodeSelected(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BoolMessage, error)
	UpdateTaskStatus(ctx context.Context, in *UpdateTaskStatusReq, opts ...grpc.CallOption) (*Empty, error)
}

type analysisClient struct {
	cc *grpc.ClientConn
}

func NewAnalysisClient(cc *grpc.ClientConn) AnalysisClient {
	return &analysisClient{cc}
}

func (c *analysisClient) GetSpotCheckList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SpotCheckListMsg, error) {
	out := new(SpotCheckListMsg)
	err := c.cc.Invoke(ctx, "/pbanalysis.Analysis/GetSpotCheckList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analysisClient) IsNodeSelected(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BoolMessage, error) {
	out := new(BoolMessage)
	err := c.cc.Invoke(ctx, "/pbanalysis.Analysis/IsNodeSelected", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analysisClient) UpdateTaskStatus(ctx context.Context, in *UpdateTaskStatusReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pbanalysis.Analysis/UpdateTaskStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalysisServer is the server API for Analysis service.
type AnalysisServer interface {
	GetSpotCheckList(context.Context, *Empty) (*SpotCheckListMsg, error)
	IsNodeSelected(context.Context, *Empty) (*BoolMessage, error)
	UpdateTaskStatus(context.Context, *UpdateTaskStatusReq) (*Empty, error)
}

// UnimplementedAnalysisServer can be embedded to have forward compatible implementations.
type UnimplementedAnalysisServer struct {
}

func (*UnimplementedAnalysisServer) GetSpotCheckList(ctx context.Context, req *Empty) (*SpotCheckListMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSpotCheckList not implemented")
}
func (*UnimplementedAnalysisServer) IsNodeSelected(ctx context.Context, req *Empty) (*BoolMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsNodeSelected not implemented")
}
func (*UnimplementedAnalysisServer) UpdateTaskStatus(ctx context.Context, req *UpdateTaskStatusReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTaskStatus not implemented")
}

func RegisterAnalysisServer(s *grpc.Server, srv AnalysisServer) {
	s.RegisterService(&_Analysis_serviceDesc, srv)
}

func _Analysis_GetSpotCheckList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServer).GetSpotCheckList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbanalysis.Analysis/GetSpotCheckList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServer).GetSpotCheckList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Analysis_IsNodeSelected_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServer).IsNodeSelected(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbanalysis.Analysis/IsNodeSelected",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServer).IsNodeSelected(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Analysis_UpdateTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServer).UpdateTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbanalysis.Analysis/UpdateTaskStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServer).UpdateTaskStatus(ctx, req.(*UpdateTaskStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Analysis_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbanalysis.Analysis",
	HandlerType: (*AnalysisServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSpotCheckList",
			Handler:    _Analysis_GetSpotCheckList_Handler,
		},
		{
			MethodName: "IsNodeSelected",
			Handler:    _Analysis_IsNodeSelected_Handler,
		},
		{
			MethodName: "UpdateTaskStatus",
			Handler:    _Analysis_UpdateTaskStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "types.proto",
}
